### ISSUE TITLE
При повторной загрузке страницы выходит ошибка The name was interpreted by this TemplateLoader

### ISSUE THREAD

**Issue by bbb1991** [bbb1991/java_spark_example#1]
Stacktrace:
`[qtp390798664-18] ERROR spark.webserver.MatcherFilter - 
java.lang.IllegalArgumentException: freemarker.template.TemplateNotFoundException: Template not found for name "hello.ftl".
The name was interpreted by this TemplateLoader: ClassTemplateLoader(resourceLoaderClass=FreeMarkerEngine, basePackagePath="/resources/").
    at FreeMarkerEngine.render(FreeMarkerEngine.java:73)
    at spark.TemplateViewRouteImpl$1.render(TemplateViewRouteImpl.java:61)
    at spark.TemplateViewRouteImpl$1.render(TemplateViewRouteImpl.java:58)
    at spark.TemplateViewRouteImpl.render(TemplateViewRouteImpl.java:85)
    at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:164)
    at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "hello.ftl".
The name was interpreted by this TemplateLoader: ClassTemplateLoader(resourceLoaderClass=FreeMarkerEngine, basePackagePath="/resources/").
    at freemarker.template.Configuration.getTemplate(Configuration.java:2430)
    at freemarker.template.Configuration.getTemplate(Configuration.java:2232)
    at FreeMarkerEngine.render(FreeMarkerEngine.java:67)
    ... 19 more`

**Comment by bbb1991** [comment]
Ошибка была у меня в коде. При конфигураций FreeMarker, указывал что нужно брать шаблоны из папки resources, где они и лежат фактический до компиляций. Но оказывается при компиляций все файлы шаблонов и байт коды падают в одну папку и потом оттуда и берутся
